### ISSUE TITLE
Karma-openui5 future

### ISSUE THREAD

**Issue by DenisTis** [SAP/karma-openui5#12]
Is it planned to support this plugin? 
Would karma version be updated to latest at some time?
Is there support of sinon planned?

**Comment by RandomByte** [comment]
I'm sorry, but I'm having problems understanding your questions.

> Is it planned to support this plugin?

What kind of support do you mean?

> Would karma version be updated to latest at some time?

This plugin already supports Karma 2.0 which is the latest version currently available. You can see this in action in the OpenUI5 Sample App: https://github.com/SAP/openui5-sample-app

> Is there support of sinon planned?

You should be able to just use Sinon. Did you experience any issues in conjunction with this plugin?

**Comment by DenisTis** [comment]
Hi RandomByte, 
thank you for the information.
I was not aware of openui5-sample-app and was using outdated karma-openui5-sample project.

The issue is closed.

**Comment by RandomByte** [comment]
Glad to hear that. Was that the same root issue that caused https://github.com/karma-runner/karma/issues/2928?
