### ISSUE TITLE
All the tests are failed

### ISSUE THREAD

**Issue by yingzoe** [SAP/karma-openui5#13]
I'm using mock data. When I run karma, in the opened browser, I can see the mock data but tests are failed because _unable to retireve the entity set Projects_. If I run the tests without karma, tests can pass with mock data.
Below is my configuration file:
`module.exports = function (config) {
    config.set({
        basePath: '../../',
        frameworks: ['openui5','qunit'],
        plugins: ['karma-qunit', 'karma-chrome-launcher', 'karma-openui5', 'karma-coverage'],

        files: [
             {
                 pattern: 'public/test/AllTestsKarma.js',
                 served: true,
                 watched: false,
                 included: true
             },
            {
                pattern: 'public/**/*',
                served: true,
                watched: false,
                included: false
            }
        ],

        browserNoActivityTimeout: 50000,

        preprocessors: {
            'public/common/controller/*.js': ['coverage'],
            'public/common/model/*.js': ['coverage'],
            'public/precheck/controller/*.js': ['coverage']

        },
        openui5: {
            path: 'https://sapui5.hana.ondemand.com/1.46.6/resources/sap-ui-core.js',
            useMockServer: true
        },
        client: {
            openui5: {
                config: {
                    theme: "sap_belize",
                    libs: "sap.ushell,sap.m",
                    compatVersion: 'edge',
                    resourceroots: {
                         "sap.ui.scpint": "/base/public",
                         "test.unit": "/base/public/test/unit",
                         "test.integration": "/base/public/test/integration"
                    }
                    
                },
                mockserver: {
                    config: {
                        autoRespond: true
                    },
                    rootUri: '/odata/Precheck.svc/',
                    metadataURL: '/base/public/localService/metadata.xml',
                    mockdataSettings:  {'sMockdataBaseUrl':'/base/public/localService/mockdata/','bGenerateMissingMockData' : false}
                }
            }
        },
        reporters: ['progress', 'coverage'],
        proxies: {
            '/test/': '/base/public/test/',
            '/sap/ui/scpint/': '/base/public/',
            '/resources': 'https://sapui5.hana.ondemand.com/1.46.6/resources',
            '/test-resources': 'https://sapui5.hana.ondemand.com/test-resources'
        },
        port: 9876,
        colors: true,
        logLevel: config.LOG_INFO,
        autoWatch: false,
        browsers: ['Chrome'],
        singleRun: true
    });
};`

What's wrong with it?

**Comment by yingzoe** [comment]
Now tests are SUCCESS. 
But I got something from command line which confuses me:

> DEBUG: '2018-03-15 18:29:54.067600 [context.html] Control 'Element sap.m.List#__xmlview1--masterView--projectList' has 0 Objects in the aggregation 'items' but it should have 3 -  sap.ui.test.matchers.AggregationLengthEquals'

One of my assert checks if there are three projects in the project list. If it passed, why does it say has 0 Objects in the aggregation 'items'?

**Comment by matz3** [comment]
This also seems strange to me. Does this also happen when running the tests without karma (e.g. with a HTML test page)?

**Comment by yingzoe** [comment]
I just noticed that this message is displayed before the aggregation 'items' gets the real count...Before timeout, it will get the real count thus tests pass.

**Comment by matz3** [comment]
Ah, that makes sense. So all issues are solved now, right?

**Comment by yingzoe** [comment]
Yes, sorry for the delay...
