### ISSUE TITLE
Mock data fails to load for OPA5 tests

### ISSUE THREAD

**Issue by amit1agrawal** [SAP/karma-openui5#7]
Hi ,
I copied the code in my https://github.com/jasper07/karmatest ( @jarus) to test it. I have done the changes as suggested by @matz3 that is to load 'openui5' framework before 'qunit' 
frameworks: ['openui5','qunit']
So there is no issue with loading of MockServer.js but mock data is not getting loaded. I have set the log level to DEBUG and nowhere I could see that the mock data json files are being loaded/served. Also, in chrome network log, there is an entry to load metadata.xml from actual service (which fails of course). 
To verify that there is nothing else wrong with the project,  I deployed the same on WebIDE and its loading fine with mock data over there.
Am I doing something wrong? I can provide the debug log files if required.

Thanks in advance.

**Comment by matz3** [comment]
Hey @amit1agrawal 
This does not sound like an issue with this karma plugin in first place. And it's hard to guess what could be wrong just with your description. If you could provide a sample project where this can be reproduced I can quickly have a look into it.

Please consider using StackOverflow to get help for such kind of issues.

**Comment by amit1agrawal** [comment]
Hi @matz3 ,
Sorry, my bad :( . I thought it's some issue with running under mockserver and works fine with actual service.
You can download the code from git@github.com:amit1agrawal/karmatestwithMS.git
Thanks for the help.
If not resolved I will post it in Stackoverflow.

**Comment by matz3** [comment]
@amit1agrawal your `mockserver` config is on the wrong level thus the MockServer is started without any configuration.

In your project it is within `client.openui5.config` while the [README] (https://github.com/SAP/karma-openui5/blob/master/README.md) describes it within `client.openui5` (no `config`!).

**Comment by amit1agrawal** [comment]
@matz3  Thanks a lot! Let me try with that.
