### ISSUE TITLE
Unable to run Gherkin tests with Karma

### ISSUE THREAD

**Issue by steeren** [SAP/karma-openui5#8]
I'm really at a loss as to how to get Karma and Gherkin to work together. It seems both Karma and Gherkin want to start the test runner. I was hoping to find a place where could configure Gherkin not to start the test, only load.

I get the following:

`
Chrome 55.0.2883 (Windows 7 0.0.0) ERROR
  Uncaught Error: Called start() outside of a test context while already started
  at http://localhost:9876/baseThirdparty/dist/sap/ui/thirdparty/qunit.js:287
`

I'm using Openui5 1.42.6 and karma-openui5 0.2.1

In other tests trials, the workaround for crossroads/mockserver seems to be causing problems

`Chrome 55.0.2883 (Windows 7 0.0.0) ERROR
  Uncaught ReferenceError: module is not defined
  at node_modules/karma-openui5/lib/mockserver.js:9
`

**Comment by matz3** [comment]
Hey @steeren, can you share your project so that I may have a look into it?

**Comment by steeren** [comment]
No I can’t share the code, but I can build a simpler example. Will take me a little while right now though.

**Comment by smilingsun** [comment]
Hi @steeren ,

I tried to run gherkin OPA and succeeded, that this is my ``karma-main.js``:
```
(function (karma) {
	"use strict";

	// Prevent Karma from running prematurely.
	karma.loaded = function () {};

	sap.ui.getCore().attachInit(function() {
		sap.ui.require([
			"sap/support/bydchat/test/unit/allTests",
			// "sap/support/bydchat/test/integration/AllFeatures"
		], function() {
			// Finally, start Karma to run the tests.
			karma.start();
		});
	});
})(window.__karma__);
```
and my ``AllFeatures.js``:
```
QUnit.config.autostart = false;

sap.ui.require([
	"sap/ui/test/gherkin/opa5TestHarness",

	"sap/support/bydchat/localService/mockserver",
	"sap/support/bydchat/test/integration/steps/Steps",
	"sap/support/bydchat/test/integration/configureOpa"
], function(
	opa5TestHarness,
	mockserver, Steps
) {
	"use strict";
	mockserver.init();


	var aFeatures = [
		"sap.support.demo.ui.integration.features.Foo",
		"sap.support.demo.ui.integration.features.Bar",
	];

	aFeatures.forEach(function(sFeaturePath) {
		opa5TestHarness.test({
			featurePath: sFeaturePath,
			steps: Steps,
			generateMissingSteps: true
		});
	});
});

```

And I think the very important thing is this one-liner: 
```
QUnit.config.autostart = false;
```

**Comment by matz3** [comment]
@smilingsun thanks for sharing! 👍 

When using the `karma-qunit` adapter, the autostart config is set to `false` by default, see https://github.com/karma-runner/karma-qunit/blob/52eec0e8bc6d4f854de9cae2ff2213e2261e1a5b/src/adapter.wrapper#L6.
So I would expect that it also works without that line.

**Comment by matz3** [comment]
I think this can be closed
