### ISSUE TITLE
using ui5 inside the flpSandboxMockServer.html

### ISSUE THREAD

**Issue by CCFenner** [SAP/karma-openui5#9]
My opa tests are using iframes and the `flpSandboxMockServer.html`. I can run them with karma & karma-openui5 with an absolute reference to ui5 cdn inside the html file. 
Is it somehow possible to route the ui5 to use  a relative path inside the mock server file?

**Comment by matz3** [comment]
Did you already look into the `proxies` that can be configured in karma?
See: https://karma-runner.github.io/2.0/config/configuration-file.html

**Comment by stopcoder** [comment]
Hi @CCFenner,

I suppose the question is answered here with the comment from @matz3. Thus I try to close this issue report and feel free to open it again.

Best regards,
Jiawei
Dispatcher
